In [ ]:
# homework
import numpy as np

In [83]:
# homework
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
list1 = array1.reshape((5, 6))
list1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [97]:
# homework
#2.呈上題的array，找出被6除餘1的數的索引
np.where(list1 % 6 == 1)


(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))

In [96]:
np.nonzero (list1)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
        3, 4, 4, 4, 4, 4, 4]),
 array([1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4,
        5, 0, 1, 2, 3, 4, 5]))

In [76]:
a = np.array([ [0,1,2,3], [4,5,6,7], [8,9,10,11] ])
c = a.flatten() 
print('c', c)
print('a', a, '\n')
c[3] = 100
print('c', c)
print('a', a, '\n')

b = a.ravel(order='F')
print('b', b)
print('a', a, '\n')

b[3] = 100
print('b', b)
print('a', a, '\n')

d = b.reshape((2, 6))
print('d\n', d.size, '\n', d, '\n')

d[1][2] = 666
print('d\n', d.size, '\n', d, '\n')
print('b\n', b, '\n')

c [ 0  1  2  3  4  5  6  7  8  9 10 11]
a [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

c [  0   1   2 100   4   5   6   7   8   9  10  11]
a [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

b [ 0  1  2  3  4  5  6  7  8  9 10 11]
a [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

b [  0   1   2 100   4   5   6   7   8   9  10  11]
a [[  0   1   2 100]
 [  4   5   6   7]
 [  8   9  10  11]] 



In [66]:

list = np.arange(20)[3::5]  #np.arange(3, 20, step=5)
# list

list = [[1,2,3],[4,5,6]]
for row in list:
    print(row)

[1, 2, 3]
[4, 5, 6]


In [40]:
a.ravel(order='C')

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])