In [2]:
import numpy as np

In [92]:
#1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
#請寫下程式
V1 = 6324.55532033676
V0 = 20

dB = 20 * np.log10(V1/V0)
dB

30.0

In [90]:
#2.30分貝的聲壓會是50分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
V1 = np.power(10, 30 / 20 + np.log10(20))
print('V1', V1, '\n')

V2 = np.power(10, 50 / 20 + np.log10(20))
print('V2', V2, '\n')

print(V1/V2)

V1 632.4555320336759 

V2 6324.55532033676 

0.09999999999999999


In [32]:
a = [[0.1,2],
     [3,4]]
b = [5,6]
c = np.divide(a,b)
print(c)

d = np.log10(a) # log, log2, log10,   # log1p 就不清楚了
print(d)

d = np.log10(a)
print(d)

[[0.02       0.33333333]
 [0.6        0.66666667]]
[[-1.          0.30103   ]
 [ 0.47712125  0.60205999]]
[[-1.          0.30103   ]
 [ 0.47712125  0.60205999]]


In [43]:
a = [
    [[1,2],
     [3,4]],
    [[5,6],
     [7,8]]
]
b = [5,6]
c = np.multiply(a, b)
print(c)

np.e

[[[ 5 12]
  [15 24]]

 [[25 36]
  [35 48]]]


2.718281828459045

In [46]:
np.exp(np.arange(3))

array([1.        , 2.71828183, 7.3890561 ])

In [49]:
a = [
    [[1,-2],
     [3,-4]],
    [[5,-6],
     [7,-8]]
]

b = [
    [[1,-2],
     [3,-4]],
    [[5,-6],
     [7,9]]
]


np.abs(a) == np.abs(b)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True, False]]])

In [70]:
a = [[1,2],
     [3,4],
     [5,6],
    ]
b = [7,8]
c = [
    5,10
]
d = np.multiply(a, b)
print(d, '\n')
e = np.multiply(d, c)
print(e, '\n')

[[ 7 16]
 [21 32]
 [35 48]] 

[[ 35 160]
 [105 320]
 [175 480]] 



In [73]:
def map_lt(mapper, lt):
    result = []
    for ele in lt:
        result.append(mapper(ele))
    return result

lt = ['Justin', 'caterpillar', 'openhome']
print(map_lt(lambda ele: ele.upper(), lt))
print(map_lt(lambda ele: len(ele), lt))
print(type(map_lt(lambda ele: len(ele), lt)) is list)

['JUSTIN', 'CATERPILLAR', 'OPENHOME']
[6, 11, 8]
True


In [81]:
type(np.random.randint(1, 10, 20)) is list

True

In [82]:
type(np.random.randint(1, 10, 20)) is np.ndarray

True

In [85]:
np.log10(0.01)

-2.0