In [114]:
import numpy as np

english_score = np.array([55,89,76,65,48,70])
math_score    = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [115]:
#1.有多少學生英文成績比數學成績高?
npary = np.greater(english_score, math_score)
print(npary, '\n')

npary2 = npary[npary == True]
npary2.size

[False  True  True False False  True] 



3

In [120]:
#2.是否全班同學最高分都是國文?
max_ary = np.maximum(
    english_score,
    math_score
)
print(max_ary, '\n')

max_ary = np.maximum(
    max_ary,
    chinese_score
)
print(max_ary, '\n')

np.array_equal(max_ary, chinese_score)

[60 89 76 68 55 70] 

[65 90 82 72 66 77] 



True

In [121]:
np.all([
    [
        [-1, 4, 0], 
        [3, 4, 1], 
    ],
    [
        [3, 4, 1],
        [3, 0, 1], 
    ],
], axis = 0)

array([[ True,  True, False],
       [ True, False,  True]])

In [122]:
np.all([
    [
        [-1, 4, 0], 
        [3, 4, 1], 
    ],
    [
        [3, 4, 1],
        [3, 0, 1], 
    ],
], axis = 1)

array([[ True,  True, False],
       [ True, False,  True]])

In [123]:
np.all([
    [
        [-1, 4, 0], 
        [3, 4, 1], 
    ],
    [
        [3, 4, 1],
        [3, 0, 1], 
    ],
], axis = 2)

array([[False,  True],
       [ True, False]])