In [95]:
import numpy as np

In [136]:
english_score = np.array([55,89,76,65,48,70])
math_score    = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [137]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
mean_scores = np.nanmean([
    english_score,
    math_score,
    chinese_score
], axis = 1,
dtype='float16')
print('mean_scores: ', mean_scores) # 各科成績平均 en, math, chinese

max_scores = [np.nanmax(english_score), np.nanmax(math_score), np.nanmax(chinese_score)]
print('max_scores: ', max_scores) # 各科成績最大值 en, math, chinese

min_scores = [np.nanmin(english_score), np.nanmin(math_score), np.nanmin(chinese_score)]
print('min_scores: ', min_scores) # 各科成績最小值 en, math, chinese

std_scores = np.nanstd([
    english_score,
    math_score,
    chinese_score
], axis=1)
print('std_scores: ', std_scores) # 各科成績標準差 en, math, chinese

mean_scores:  [67.2 66.6 75.3]
max_scores:  [89, 85.0, 90]
min_scores:  [48, 60.0, 65]
std_scores:  [13.43399502  9.70772888  8.8254682 ]


In [138]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score    = np.array([60,85,60,68,55,60])
mean_scores = np.mean([
    english_score,
    math_score,
    chinese_score
], axis = 1,
dtype='float16')
print('mean_scores: ', mean_scores) # 各科成績平均 en, math, chinese

max_scores = [np.max(english_score), np.max(math_score), np.max(chinese_score)]
print('max_scores: ', max_scores) # 各科成績最大值 en, math, chinese

min_scores = [np.min(english_score), np.min(math_score), np.min(chinese_score)]
print('min_scores: ', min_scores) # 各科成績最小值 en, math, chinese

std_scores = np.std([
    english_score,
    math_score,
    chinese_score
], axis=1)
print('std_scores: ', std_scores) # 各科成績標準差 en, math, chinese

mean_scores:  [67.2 64.7 75.3]
max_scores:  [89, 85, 90]
min_scores:  [48, 55, 65]
std_scores:  [13.43399502  9.86013297  8.8254682 ]


In [157]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?
with_en = np.corrcoef(english_score, chinese_score)
with_math = np.corrcoef(math_score, chinese_score)
c = np.maximum(with_en, with_math)

if np.array_equal(with_en, c):
    print('與國文成績相關係數較高的是 >> 英文')
else:
    print('與國文成績相關係數較高的是 >> 數學')








與國文成績相關係數較高的是 >> 英文


In [24]:
a = [
    [ 5, 9,10,11,15,17],
    [99,23,68,92,88,float('Nan')]
]
b = [12,29,33, 7,58,13]

# 比較中的元素有 nan 的話，則會回傳 nan。
np.maximum(a, b)

array([[12., 29., 33., 11., 58., 17.],
       [99., 29., 68., 92., 88., nan]])

In [26]:
a = [
    [ 5, 9,10,11,15,17],
    [99,23,68,92,88,float('Nan')]
]
b = [12,29,33, 7,58,13]

# 比較的元素中只有一個是 nan 的話，回傳非 nan 的值，如果兩個元素都是 nan 則回傳 nan
np.fmax(a, b)

array([[12., 29., 33., 11., 58., 17.],
       [99., 29., 68., 92., 88., 13.]])

In [45]:
a = [
    [ 5, 9,10,11,15,17],
    [99,23,68,92,88,float('Nan')],
    [12,29,33, 7,58,13]
]

# median() 和 nanmedian() 不同的地方在於後者會忽略 nan。如果元素中包含 nan 的話，則 median() 會回傳 nan。
np.mean(a, axis=0, dtype='float64')

array([38.66666667, 20.33333333, 37.        , 36.66666667, 53.66666667,
               nan])

In [56]:
a = [
    [ 5, 9,10,11,15,17],
    [99,23,68,92,88,float('Nan')],
    [12,29,33, 7,58,13]
]

np.std(a, axis=0)

array([42.75771535,  8.37987006, 23.84673283, 39.16063783, 29.95923156,
               nan])

In [62]:
a = [99,23,68,92,88,26]
b = [12,29,33, 7,58,13]

np.correlate(a, b, mode='valid')

array([10185])

In [94]:
a = np.array([1,2])
b = np.array([2,1])
np.cov(a, b)
# np.cov(a, b, bias=True)

# np.vstack((a,b))
# np.cov(x)

array([[ 0.5, -0.5],
       [-0.5,  0.5]])