In [1]:
import numpy as np

In [12]:
#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('save_2_arys.npz', 'wb') as f:
    np.savez(f, aryA = array1, aryB = array2)
    

array([2, 3, 5])

In [87]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
# sol 1
part1 = np.load('save_2_arys.npz') # ['aryA', 'aryB']
part2 = np.load('multi_array.npz')

new_parts = dict(part1)
for ary_name in part2.files:
    new_parts[ary_name] = part2[ary_name]
  
# print(new_parts)

with open('new_multi_arys.npz', 'wb') as f:
    np.savez(f, **new_parts)
        
new_multi_arys = np.load('new_multi_arys.npz')
for key in new_multi_arys.files:
    print(key, new_multi_arys[key])

aryA [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
aryB [2 3 5]
array1 [0 1 2 3 4 5 6 7 8 9]
array2 [1 2 3]
array3 [0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]


In [88]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
# sol 2
part1 = np.load('save_2_arys.npz')
part2 = np.load('multi_array.npz')

part1 = dict(part1)
part2 = dict(part2)

new_part = part1.update(part2)
  
print(new_parts)

with open('new_multi_arys.npz', 'wb') as f:
    np.savez(f, **new_parts)
        
new_multi_arys = np.load('new_multi_arys.npz')
for key in new_multi_arys.files:
    print(key, new_multi_arys[key])

{'aryA': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), 'aryB': array([2, 3, 5]), 'array1': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'array2': array([1, 2, 3]), 'array3': array([0.5788873 , 0.69082947, 0.04922545, 0.86517602, 0.29889969,
       0.55285575, 0.69389689, 0.49183867, 0.8308363 , 0.06454569])}
aryA [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
aryB [2 3 5]
array1 [0 1 2 3 4 5 6 7 8 9]
array2 [1 2 3]
array3 [0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]


In [3]:
with open('one_array.npy', 'wb') as f:
    np.save(f, np.array([1, 2]))
    
np.load('one_array.npy')

array([1, 2])

In [8]:
x = np.arange(10)
y = np.array([1,2,3])
z = np.random.rand(10)

with open('mutli_array.npz', 'wb') as f:
    np.savez(f, ary1=x, ary2=y, aryC=z)
    
npzfile = np.load('mutli_array.npz')
print( type(npzfile)  )

print(npzfile['ary1'])
print(npzfile['ary2'])
print(npzfile['aryC'])

<class 'numpy.lib.npyio.NpzFile'>
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.98655823 0.68671685 0.4312876  0.86973333 0.19622295 0.21114048
 0.05645112 0.27710756 0.43560955 0.73116032]


In [9]:
# save as .txt

x = np.arange(10)
y = np.array([1,2,3])
z = np.random.rand(10)

np.savetxt('test.out', x, fmt='%1.4e', delimiter=',', header='this is, \nheader', footer='this is footer')