In [1]:
import numpy as np

In [7]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
antiArray1 = np.linalg.inv(array1)

print(antiArray1)

print(np.matmul(antiArray1, array1))
print(np.matmul(array1, antiArray1))
print(antiArray1 @ array1)
print(array1 @ antiArray1)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [8]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)

print(w)
print(v)

[13.  2.]
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [ ]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)

pri